import { initializeApp } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js";
import { getStorage } from "https://www.gstatic.com/firebasejs/10.12.5/firebase-storage.js";
import { firebaseConfig } from "./firebase_config.js";

// firebase_config.js is generated by GitHub Actions for Pages deploys.
// For local development, copy firebase_config.example.js to firebase_config.js.
const app = initializeApp(firebaseConfig);
export const storage = getStorage(app);
